version: '3.9'
services:
  # PostgreSQL service
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: hienphamm
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Golang application service
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: movies
      DB_PASSWORD: hienphamm
      DB_NAME: secret
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
