POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "email": "hienpham@gmail.com",
  "password": "mysecretpassword"
}
###
GET http://localhost:8080/movies
Content-Type: application/json

###
GET https://cdn.contentstack.io/